version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}mogambo08/testapi
    depends_on:
      - "app_db"
    container_name: c_testapi
    ports:
      - "1000:80"
      - "1001:1000"
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=SampleDbDriver;IntegratedSecurity=true;Pooling=true
      - ASPNETCORE_URLS=http://+:80
    networks: 
      - dev
 
  app_db:
    image: postgres:latest
    container_name: app_db
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=SampleDbDriver 
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - /opt/app_data/postgres:/var/lib/postgresql/pgdata
    networks:
      - dev
